name: Theological Guardrails Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  theological-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for better diff analysis

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pyyaml

      - name: Get changed files
        id: changed-files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, compare with base branch
            git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt
          else
            # For pushes, compare with previous commit
            git diff --name-only HEAD~1...HEAD > changed_files.txt
          fi
          
          # Filter for gamaliel-prompts files only
          grep "^gamaliel-prompts/" changed_files.txt > filtered_files.txt || true
          
          # Create JSON array of changed files
          echo "changed_files=$(cat filtered_files.txt | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          
          echo "Changed files in gamaliel-prompts:"
          cat filtered_files.txt

      - name: Review theological content
        id: review
        run: |
          python .github/scripts/theological_reviewer.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.review.outputs.violations != ''
        uses: actions/github-script@v7
        with:
          script: |
            const violations = '${{ steps.review.outputs.violations }}';
            const details = '${{ steps.review.outputs.details }}';
            
            const comment = `## ⚠️ Theological Guardrails Violation Detected

            This PR contains changes that violate the mandatory core theological guardrails defined in \`guardrails.md\`.

            ### Violations Found:
            ${violations}

            ### Details:
            ${details}

            **Action Required:** Please review and revise the content to ensure it aligns with the core Christian doctrines and theological guardrails before this PR can be merged.

            ---
            *This review was performed by the Theological Guardrails Review system.*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail on violations
        if: steps.review.outputs.violations != ''
        run: |
          echo "❌ Theological guardrails violations detected. PR cannot be merged."
          echo "Violations: ${{ steps.review.outputs.violations }}"
          exit 1

      - name: Success message
        if: steps.review.outputs.violations == ''
        run: |
          echo "✅ All changes comply with theological guardrails"
          echo "PR is approved from a theological perspective" 